### PR TITLE
get GRAPH_HEIGHT from configure

### PR DESCRIPTION
**Pull request by eworm-de**
Signed-off-by: Christian Hesse mail@eworm.de

### CODE REVIEW

**Comment by Explorer09** [comment]
I never expect this thing become a configure option. Well, I expect (ideally) that thing being a runtime option with a reasonable maximum (a GRAPH_HEIGHT_MAX macro or something like that) in code.
Anyway, I think you would better write out the default height in the help string.

**Comment by eworm-de** [comment]
Just wanted this for myself for testing purpose. ;)
Adding a runtime option should be straight forward...

**Comment by Explorer09** [comment]
And by the way, if I were the original project owner, I would not merge this.
Because I'm not sure how other users will interpret such a `configure` implementation. As an example, what if a user configures `--without-graph-height` ? This option may be good for testing, but IMHO it won't be ideal for a release version. I hope you don't mind if I close this one just on my fork.

**Comment by eworm-de** [comment]
Valid point... `--without-graph-height` defines `GRAPH_HEIGHT` to `no`.
Never mind, I am fine with closing it.

**Pull request closed without merging**
